### PR TITLE
Fix "-T option null" issue

### PR DESCRIPTION
**Pull request by unverbraucht**
## Summary

When #144 was merged I missed a check to see if device_topic_suffix is null. This causes issues #155 and #159 . This PR adds a simple config check and fixes the issue for me when I don't add this argument.

## Alternatives Considered

There are other PRs that also fix this issue but this is a simple one-liner. I also ported the changes to config.json from the next folder over to the main autodiscovery config.json so these options work once next is merged.

## Testing Steps

1. Run next without setting a value for device_topic_suffix
2. Add-On should start up

### CODE REVIEW

**Comment by catduckgnaf** [comment]
Nah, they want to wait months for "upstream" to fix it instead. 
mine was a one liner too. 

I decided to spend effort on actually making an integration that people want.

**Comment by unverbraucht** [comment]
> Nah, they want to wait months for "upstream" to fix it instead. mine was a one liner too.
> 
> I decided to spend effort on actually making an integration that people want.

This has not been my experience with this project.

Since I was the person introducing the bug (sorry about that) I think it's fair that I fix it :)

**Comment by unverbraucht** [comment]
@catduckgnaf since you also fixed the issue in your branch (along many improvements, cudos!) could you review this PR?

**Review by catduckgnaf — APPROVED** [review]

**Comment by benklop** [comment]
This is actually caused by the path to the image being incorrect: https://github.com/pbkhrv/rtl_433-hass-addons/pull/164 is probably the right fix

**Comment by deviantintegral** [comment]
Agreed with going with #164. Closing this one for now, but if someone thinks we'll need _both_ changes then feel free to reopen.

**Comment by unverbraucht** [comment]
Absolutely fine with the other fix if it fixes things :)

**Pull request closed without merging**
